import {
  SignJWT,
  createRemoteJWKSet,
  jwtVerify,
} from "jose";

const GOOGLE_ISSUER = "https://accounts.google.com";

const GOOGLE_JWKS_URL = new URL(
  "https://www.googleapis.com/oauth2/v3/certs",
);

function getGoogleClientId(): string {
  const value = process.env.GOOGLE_CLIENT_ID?.trim();

  if (!value) {
    throw new Error(
      "GOOGLE_CLIENT_ID chưa được cấu hình",
    );
  }

  return value;
}

function getGoogleClientSecret(): string {
  const value =
    process.env.GOOGLE_CLIENT_SECRET?.trim();

  if (!value) {
    throw new Error(
      "GOOGLE_CLIENT_SECRET chưa được cấu hình",
    );
  }

  return value;
}

function getStateSecret(): Uint8Array {
  const secret =
    process.env.JWT_SECRET?.trim() ||
    "change-this-secret-in-production-min-32-chars!!";

  if (secret.length < 32) {
    throw new Error(
      "JWT_SECRET phải có ít nhất 32 ký tự",
    );
  }

  return new TextEncoder().encode(secret);
}

export type GoogleOAuthMode = "login" | "link";

export interface GoogleOAuthState {
  mode: GoogleOAuthMode;
  userId?: string;
  nonce: string;
}

export interface GoogleProfile {
  sub: string;
  email: string;
  emailVerified: boolean;
  name: string | null;
  picture: string | null;
}

/**
 * Create a signed OAuth state.
 *
 * The state is signed using the same server-side JWT secret used by Orca.
 * It is also stored in a short-lived httpOnly cookie by the OAuth start route.
 */
export async function createGoogleOAuthState(
  payload: GoogleOAuthState,
): Promise<string> {
  const jwtPayload = {
    mode: payload.mode,
    ...(payload.userId
      ? { userId: payload.userId }
      : {}),
    nonce: payload.nonce,
  };

  return new SignJWT(jwtPayload)
    .setProtectedHeader({
      alg: "HS256",
    })
    .setIssuedAt()
    .setExpirationTime("10m")
    .sign(getStateSecret());
}

/**
 * Verify OAuth state generated by createGoogleOAuthState().
 */
export async function verifyGoogleOAuthState(
  state: string,
): Promise<GoogleOAuthState | null> {
  try {
    const { payload } = await jwtVerify(
      state,
      getStateSecret(),
      {
        algorithms: ["HS256"],
      },
    );

    if (
      payload.mode !== "login" &&
      payload.mode !== "link"
    ) {
      return null;
    }

    if (typeof payload.nonce !== "string") {
      return null;
    }

    if (
      payload.mode === "link" &&
      typeof payload.userId !== "string"
    ) {
      return null;
    }

    return {
      mode: payload.mode,
      userId:
        typeof payload.userId === "string"
          ? payload.userId
          : undefined,
      nonce: payload.nonce,
    };
  } catch {
    return null;
  }
}

/**
 * Build the Google authorization URL.
 */
export function buildGoogleAuthorizationUrl(
  redirectUri: string,
  state: string,
): string {
  const clientId = getGoogleClientId();

  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    response_type: "code",
    scope: "openid email profile",
    state,
    access_type: "offline",
    prompt: "select_account",
  });

  return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
}

/**
 * Exchange Google's authorization code for tokens.
 */
export async function exchangeGoogleCode(
  code: string,
  redirectUri: string,
): Promise<{
  idToken: string;
}> {
  const clientId = getGoogleClientId();
  const clientSecret = getGoogleClientSecret();

  const body = new URLSearchParams({
    code,
    client_id: clientId,
    client_secret: clientSecret,
    redirect_uri: redirectUri,
    grant_type: "authorization_code",
  });

  const response = await fetch(
    "https://oauth2.googleapis.com/token",
    {
      method: "POST",
      headers: {
        "Content-Type":
          "application/x-www-form-urlencoded",
      },
      body,
      cache: "no-store",
    },
  );

  if (!response.ok) {
    const text = await response
      .text()
      .catch(() => "");

    throw new Error(
      `Google token exchange thất bại: ${text.slice(
        0,
        500,
      )}`,
    );
  }

  const json = (await response.json()) as {
    id_token?: string;
  };

  if (!json.id_token) {
    throw new Error(
      "Google không trả về ID token",
    );
  }

  return {
    idToken: json.id_token,
  };
}

const googleJwks = createRemoteJWKSet(
  GOOGLE_JWKS_URL,
);

/**
 * Verify Google's ID token using Google's public JWKS.
 */
export async function verifyGoogleIdToken(
  idToken: string,
): Promise<GoogleProfile> {
  const clientId = getGoogleClientId();

  const { payload } = await jwtVerify(
    idToken,
    googleJwks,
    {
      issuer: [
        GOOGLE_ISSUER,
        "accounts.google.com",
      ],
      audience: clientId,
    },
  );

  if (
    typeof payload.sub !== "string" ||
    !payload.sub
  ) {
    throw new Error(
      "Google ID token thiếu subject",
    );
  }

  if (
    typeof payload.email !== "string" ||
    !payload.email
  ) {
    throw new Error(
      "Google ID token thiếu email",
    );
  }

  const emailVerified =
    payload.email_verified === true ||
    payload.email_verified === "true";

  if (!emailVerified) {
    throw new Error(
      "Email Google chưa được xác thực",
    );
  }

  return {
    sub: payload.sub,
    email: payload.email.toLowerCase(),
    emailVerified: true,
    name:
      typeof payload.name === "string"
        ? payload.name
        : null,
    picture:
      typeof payload.picture === "string"
        ? payload.picture
        : null,
  };
}

/**
 * Generate a cryptographically random nonce for OAuth state.
 */
export function createOAuthNonce(): string {
  const bytes = new Uint8Array(32);

  crypto.getRandomValues(bytes);

  return Array.from(
    bytes,
    (byte) =>
      byte.toString(16).padStart(2, "0"),
  ).join("");
}
