/**
 * Standard Company Presets for Major Vietnamese Equities.
 *
 * Ensures accurate shares outstanding, quarterly revenue scale (in billion VND),
 * and financial margins for top HOSE/HNX/UPCoM listed stocks so that fallback/synthesized
 * financial statements reflect true enterprise size (e.g. BSR ~58,000B VND quarterly revenue).
 */

export interface CompanyPreset {
  symbol: string;
  name: string;
  exchange: string;
  sectorKey: string;
  sharesOutstandingMillions: number;
  baseQuarterlyRevenue: number; // billion VND
  grossMargin: number;
  operatingMargin: number;
  netMargin: number;
  leverage: number;
  currentRatio: number;
  cashPctAssets: number;
  capexToRevenue: number;
}

export const COMPANY_PRESETS: Record<string, CompanyPreset> = {
  BSR: {
    symbol: "BSR",
    name: "Công ty Cổ phần Lọc hóa dầu Bình Sơn",
    exchange: "UPCoM",
    sectorKey: "oil_refining",
    sharesOutstandingMillions: 3100.5,
    baseQuarterlyRevenue: 58200, // ~58,200 tỷ VND quý
    grossMargin: 0.08,
    operatingMargin: 0.06,
    netMargin: 0.042,
    leverage: 0.42,
    currentRatio: 1.85,
    cashPctAssets: 0.28,
    capexToRevenue: 0.02,
  },
  PLX: {
    symbol: "PLX",
    name: "Tập đoàn Xăng dầu Việt Nam",
    exchange: "HOSE",
    sectorKey: "oil_refining",
    sharesOutstandingMillions: 1293.9,
    baseQuarterlyRevenue: 72500, // ~72,500 tỷ VND quý
    grossMargin: 0.06,
    operatingMargin: 0.03,
    netMargin: 0.022,
    leverage: 0.65,
    currentRatio: 1.25,
    cashPctAssets: 0.18,
    capexToRevenue: 0.015,
  },
  GAS: {
    symbol: "GAS",
    name: "Tổng Công ty Khí Việt Nam",
    exchange: "HOSE",
    sectorKey: "energy",
    sharesOutstandingMillions: 2296.7,
    baseQuarterlyRevenue: 26800, // ~26,800 tỷ VND quý
    grossMargin: 0.21,
    operatingMargin: 0.16,
    netMargin: 0.138,
    leverage: 0.32,
    currentRatio: 2.1,
    cashPctAssets: 0.42,
    capexToRevenue: 0.05,
  },
  HPG: {
    symbol: "HPG",
    name: "Tập đoàn Hòa Phát",
    exchange: "HOSE",
    sectorKey: "steel",
    sharesOutstandingMillions: 5814.7,
    baseQuarterlyRevenue: 38500, // ~38,500 tỷ VND quý
    grossMargin: 0.16,
    operatingMargin: 0.11,
    netMargin: 0.088,
    leverage: 0.48,
    currentRatio: 1.45,
    cashPctAssets: 0.18,
    capexToRevenue: 0.08,
  },
  VNM: {
    symbol: "VNM",
    name: "Công ty Cổ phần Sữa Việt Nam",
    exchange: "HOSE",
    sectorKey: "consumer_staples",
    sharesOutstandingMillions: 2089.9,
    baseQuarterlyRevenue: 16800, // ~16,800 tỷ VND quý
    grossMargin: 0.42,
    operatingMargin: 0.21,
    netMargin: 0.165,
    leverage: 0.35,
    currentRatio: 1.95,
    cashPctAssets: 0.28,
    capexToRevenue: 0.04,
  },
  FPT: {
    symbol: "FPT",
    name: "Công ty Cổ phần FPT",
    exchange: "HOSE",
    sectorKey: "technology",
    sharesOutstandingMillions: 1460.5,
    baseQuarterlyRevenue: 16200, // ~16,200 tỷ VND quý
    grossMargin: 0.38,
    operatingMargin: 0.19,
    netMargin: 0.155,
    leverage: 0.45,
    currentRatio: 1.55,
    cashPctAssets: 0.28,
    capexToRevenue: 0.06,
  },
  MWG: {
    symbol: "MWG",
    name: "Công ty Cổ phần Đầu tư Thế Giới Di Động",
    exchange: "HOSE",
    sectorKey: "retail",
    sharesOutstandingMillions: 1462.2,
    baseQuarterlyRevenue: 36500, // ~36,500 tỷ VND quý
    grossMargin: 0.23,
    operatingMargin: 0.045,
    netMargin: 0.032,
    leverage: 0.58,
    currentRatio: 1.25,
    cashPctAssets: 0.15,
    capexToRevenue: 0.03,
  },
  VIC: {
    symbol: "VIC",
    name: "Tập đoàn Vingroup",
    exchange: "HOSE",
    sectorKey: "conglomerate",
    sharesOutstandingMillions: 3823.7,
    baseQuarterlyRevenue: 52000, // ~52,000 tỷ VND quý
    grossMargin: 0.22,
    operatingMargin: 0.08,
    netMargin: 0.025,
    leverage: 0.78,
    currentRatio: 1.15,
    cashPctAssets: 0.06,
    capexToRevenue: 0.12,
  },
  VHM: {
    symbol: "VHM",
    name: "Công ty Cổ phần Vinhomes",
    exchange: "HOSE",
    sectorKey: "real_estate",
    sharesOutstandingMillions: 4354.4,
    baseQuarterlyRevenue: 32000, // ~32,000 tỷ VND quý
    grossMargin: 0.45,
    operatingMargin: 0.35,
    netMargin: 0.265,
    leverage: 0.58,
    currentRatio: 1.45,
    cashPctAssets: 0.08,
    capexToRevenue: 0.02,
  },
  MSN: {
    symbol: "MSN",
    name: "Công ty Cổ phần Tập đoàn Masan",
    exchange: "HOSE",
    sectorKey: "conglomerate",
    sharesOutstandingMillions: 1430.8,
    baseQuarterlyRevenue: 22500, // ~22,500 tỷ VND quý
    grossMargin: 0.29,
    operatingMargin: 0.085,
    netMargin: 0.028,
    leverage: 0.72,
    currentRatio: 1.1,
    cashPctAssets: 0.09,
    capexToRevenue: 0.05,
  },
  VCB: {
    symbol: "VCB",
    name: "Ngân hàng TMCP Ngoại thương Việt Nam",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 5589.1,
    baseQuarterlyRevenue: 21500, // TOI ~21,500 tỷ VND quý
    grossMargin: 0.68,
    operatingMargin: 0.52,
    netMargin: 0.415,
    leverage: 0.9,
    currentRatio: 0,
    cashPctAssets: 0.1,
    capexToRevenue: 0.02,
  },
  TCB: {
    symbol: "TCB",
    name: "Ngân hàng TMCP Kỹ thương Việt Nam",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 7045.5,
    baseQuarterlyRevenue: 13500,
    grossMargin: 0.65,
    operatingMargin: 0.48,
    netMargin: 0.385,
    leverage: 0.88,
    currentRatio: 0,
    cashPctAssets: 0.1,
    capexToRevenue: 0.02,
  },
  MBB: {
    symbol: "MBB",
    name: "Ngân hàng TMCP Quân đội",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 5287.1,
    baseQuarterlyRevenue: 14200,
    grossMargin: 0.62,
    operatingMargin: 0.45,
    netMargin: 0.365,
    leverage: 0.89,
    currentRatio: 0,
    cashPctAssets: 0.1,
    capexToRevenue: 0.02,
  },
  SAB: {
    symbol: "SAB",
    name: "Tổng Công ty Cổ phần Bia - Rượu - Nước giải khát Sài Gòn",
    exchange: "HOSE",
    sectorKey: "consumer_staples",
    sharesOutstandingMillions: 1282.6,
    baseQuarterlyRevenue: 8800,
    grossMargin: 0.31,
    operatingMargin: 0.18,
    netMargin: 0.142,
    leverage: 0.28,
    currentRatio: 2.2,
    cashPctAssets: 0.38,
    capexToRevenue: 0.03,
  },
  POW: {
    symbol: "POW",
    name: "Tổng Công ty Điện lực Dầu khí Việt Nam",
    exchange: "HOSE",
    sectorKey: "utilities",
    sharesOutstandingMillions: 2341.8,
    baseQuarterlyRevenue: 8200,
    grossMargin: 0.14,
    operatingMargin: 0.09,
    netMargin: 0.065,
    leverage: 0.48,
    currentRatio: 1.35,
    cashPctAssets: 0.15,
    capexToRevenue: 0.1,
  },
  PVD: {
    symbol: "PVD",
    name: "Tổng Công ty Cổ phần Khoan và Dịch vụ Khoan Dầu khí",
    exchange: "HOSE",
    sectorKey: "energy",
    sharesOutstandingMillions: 556.1,
    baseQuarterlyRevenue: 2100,
    grossMargin: 0.24,
    operatingMargin: 0.15,
    netMargin: 0.105,
    leverage: 0.38,
    currentRatio: 1.65,
    cashPctAssets: 0.18,
    capexToRevenue: 0.08,
  },
  PVS: {
    symbol: "PVS",
    name: "Tổng Công ty Cổ phần Dịch vụ Kỹ thuật Dầu khí Việt Nam",
    exchange: "HNX",
    sectorKey: "energy",
    sharesOutstandingMillions: 478.0,
    baseQuarterlyRevenue: 5500,
    grossMargin: 0.09,
    operatingMargin: 0.06,
    netMargin: 0.048,
    leverage: 0.45,
    currentRatio: 1.75,
    cashPctAssets: 0.38,
    capexToRevenue: 0.05,
  },
  GVR: {
    symbol: "GVR",
    name: "Tập đoàn Công nghiệp Cao su Việt Nam",
    exchange: "HOSE",
    sectorKey: "materials",
    sharesOutstandingMillions: 4000.0,
    baseQuarterlyRevenue: 7200,
    grossMargin: 0.24,
    operatingMargin: 0.16,
    netMargin: 0.125,
    leverage: 0.35,
    currentRatio: 1.8,
    cashPctAssets: 0.22,
    capexToRevenue: 0.06,
  },
  SSI: {
    symbol: "SSI",
    name: "Công ty Cổ phần Chứng khoán SSI",
    exchange: "HOSE",
    sectorKey: "securities",
    sharesOutstandingMillions: 1964.3,
    baseQuarterlyRevenue: 2400,
    grossMargin: 0.58,
    operatingMargin: 0.42,
    netMargin: 0.325,
    leverage: 0.55,
    currentRatio: 1.35,
    cashPctAssets: 0.28,
    capexToRevenue: 0.02,
  },
  VND: {
    symbol: "VND",
    name: "Công ty Cổ phần Chứng khoán VNDIRECT",
    exchange: "HOSE",
    sectorKey: "securities",
    sharesOutstandingMillions: 1522.3,
    baseQuarterlyRevenue: 1800,
    grossMargin: 0.55,
    operatingMargin: 0.38,
    netMargin: 0.285,
    leverage: 0.58,
    currentRatio: 1.3,
    cashPctAssets: 0.25,
    capexToRevenue: 0.02,
  },
  VCI: {
    symbol: "VCI",
    name: "Công ty Cổ phần Chứng khoán Vietcap",
    exchange: "HOSE",
    sectorKey: "securities",
    sharesOutstandingMillions: 718.0,
    baseQuarterlyRevenue: 1200,
    grossMargin: 0.58,
    operatingMargin: 0.40,
    netMargin: 0.31,
    leverage: 0.52,
    currentRatio: 1.4,
    cashPctAssets: 0.30,
    capexToRevenue: 0.02,
  },
  HCM: {
    symbol: "HCM",
    name: "Công ty Cổ phần Chứng khoán TP.HCM (HSC)",
    exchange: "HOSE",
    sectorKey: "securities",
    sharesOutstandingMillions: 704.8,
    baseQuarterlyRevenue: 1150,
    grossMargin: 0.56,
    operatingMargin: 0.39,
    netMargin: 0.295,
    leverage: 0.54,
    currentRatio: 1.35,
    cashPctAssets: 0.28,
    capexToRevenue: 0.02,
  },
  MBS: {
    symbol: "MBS",
    name: "Công ty Cổ phần Chứng khoán MB",
    exchange: "HNX",
    sectorKey: "securities",
    sharesOutstandingMillions: 437.6,
    baseQuarterlyRevenue: 750,
    grossMargin: 0.52,
    operatingMargin: 0.35,
    netMargin: 0.26,
    leverage: 0.58,
    currentRatio: 1.3,
    cashPctAssets: 0.25,
    capexToRevenue: 0.02,
  },
  FTS: {
    symbol: "FTS",
    name: "Công ty Cổ phần Chứng khoán FPT",
    exchange: "HOSE",
    sectorKey: "securities",
    sharesOutstandingMillions: 305.9,
    baseQuarterlyRevenue: 380,
    grossMargin: 0.62,
    operatingMargin: 0.45,
    netMargin: 0.35,
    leverage: 0.42,
    currentRatio: 1.5,
    cashPctAssets: 0.35,
    capexToRevenue: 0.02,
  },
  BID: {
    symbol: "BID",
    name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 5700.4,
    baseQuarterlyRevenue: 19500,
    grossMargin: 0.66,
    operatingMargin: 0.48,
    netMargin: 0.38,
    leverage: 0.91,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  CTG: {
    symbol: "CTG",
    name: "Ngân hàng TMCP Công thương Việt Nam",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 5370.0,
    baseQuarterlyRevenue: 18200,
    grossMargin: 0.65,
    operatingMargin: 0.46,
    netMargin: 0.36,
    leverage: 0.90,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  ACB: {
    symbol: "ACB",
    name: "Ngân hàng TMCP Á Châu",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 4466.6,
    baseQuarterlyRevenue: 8500,
    grossMargin: 0.64,
    operatingMargin: 0.46,
    netMargin: 0.37,
    leverage: 0.88,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  VPB: {
    symbol: "VPB",
    name: "Ngân hàng TMCP Việt Nam Thịnh Vượng",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 7934.0,
    baseQuarterlyRevenue: 15800,
    grossMargin: 0.60,
    operatingMargin: 0.40,
    netMargin: 0.28,
    leverage: 0.87,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  SHB: {
    symbol: "SHB",
    name: "Ngân hàng TMCP Sài Gòn - Hà Nội",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 3662.4,
    baseQuarterlyRevenue: 6200,
    grossMargin: 0.58,
    operatingMargin: 0.38,
    netMargin: 0.29,
    leverage: 0.90,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  EIB: {
    symbol: "EIB",
    name: "Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 1740.3,
    baseQuarterlyRevenue: 2800,
    grossMargin: 0.56,
    operatingMargin: 0.34,
    netMargin: 0.25,
    leverage: 0.89,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  LPB: {
    symbol: "LPB",
    name: "Ngân hàng TMCP Lộc Phát Việt Nam",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 2557.6,
    baseQuarterlyRevenue: 4200,
    grossMargin: 0.58,
    operatingMargin: 0.38,
    netMargin: 0.29,
    leverage: 0.89,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  STB: {
    symbol: "STB",
    name: "Ngân hàng TMCP Sài Gòn Thương Tín",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 1885.2,
    baseQuarterlyRevenue: 7200,
    grossMargin: 0.58,
    operatingMargin: 0.38,
    netMargin: 0.28,
    leverage: 0.91,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  HDB: {
    symbol: "HDB",
    name: "Ngân hàng TMCP Phát triển TP.HCM",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 2907.6,
    baseQuarterlyRevenue: 7800,
    grossMargin: 0.60,
    operatingMargin: 0.42,
    netMargin: 0.32,
    leverage: 0.89,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  TPB: {
    symbol: "TPB",
    name: "Ngân hàng TMCP Tiên Phong",
    exchange: "HOSE",
    sectorKey: "banking",
    sharesOutstandingMillions: 2201.6,
    baseQuarterlyRevenue: 4500,
    grossMargin: 0.58,
    operatingMargin: 0.38,
    netMargin: 0.28,
    leverage: 0.88,
    currentRatio: 0,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  HSG: {
    symbol: "HSG",
    name: "Công ty Cổ phần Tập đoàn Hoa Sen",
    exchange: "HOSE",
    sectorKey: "steel",
    sharesOutstandingMillions: 616.0,
    baseQuarterlyRevenue: 10500,
    grossMargin: 0.12,
    operatingMargin: 0.05,
    netMargin: 0.032,
    leverage: 0.52,
    currentRatio: 1.25,
    cashPctAssets: 0.08,
    capexToRevenue: 0.04,
  },
  NKG: {
    symbol: "NKG",
    name: "Công ty Cổ phần Thép Nam Kim",
    exchange: "HOSE",
    sectorKey: "steel",
    sharesOutstandingMillions: 263.2,
    baseQuarterlyRevenue: 5200,
    grossMargin: 0.10,
    operatingMargin: 0.045,
    netMargin: 0.028,
    leverage: 0.55,
    currentRatio: 1.2,
    cashPctAssets: 0.08,
    capexToRevenue: 0.04,
  },
  DGC: {
    symbol: "DGC",
    name: "Công ty Cổ phần Tập đoàn Hóa chất Đức Giang",
    exchange: "HOSE",
    sectorKey: "steel",
    sharesOutstandingMillions: 379.7,
    baseQuarterlyRevenue: 3100,
    grossMargin: 0.35,
    operatingMargin: 0.26,
    netMargin: 0.225,
    leverage: 0.22,
    currentRatio: 2.8,
    cashPctAssets: 0.45,
    capexToRevenue: 0.06,
  },
  DPM: {
    symbol: "DPM",
    name: "Tổng Công ty Phân bón và Hóa chất Dầu khí",
    exchange: "HOSE",
    sectorKey: "steel",
    sharesOutstandingMillions: 391.4,
    baseQuarterlyRevenue: 3800,
    grossMargin: 0.22,
    operatingMargin: 0.12,
    netMargin: 0.095,
    leverage: 0.28,
    currentRatio: 2.1,
    cashPctAssets: 0.42,
    capexToRevenue: 0.04,
  },
  DCM: {
    symbol: "DCM",
    name: "Công ty Cổ phần Phân bón Dầu khí Cà Mau",
    exchange: "HOSE",
    sectorKey: "steel",
    sharesOutstandingMillions: 529.4,
    baseQuarterlyRevenue: 3600,
    grossMargin: 0.24,
    operatingMargin: 0.14,
    netMargin: 0.115,
    leverage: 0.25,
    currentRatio: 2.3,
    cashPctAssets: 0.48,
    capexToRevenue: 0.04,
  },
  DXG: {
    symbol: "DXG",
    name: "Công ty Cổ phần Tập đoàn Đất Xanh",
    exchange: "HOSE",
    sectorKey: "real_estate",
    sharesOutstandingMillions: 721.7,
    baseQuarterlyRevenue: 1400,
    grossMargin: 0.42,
    operatingMargin: 0.22,
    netMargin: 0.12,
    leverage: 0.55,
    currentRatio: 1.35,
    cashPctAssets: 0.12,
    capexToRevenue: 0.02,
  },
  DIG: {
    symbol: "DIG",
    name: "Tổng Công ty Cổ phần Đầu tư Phát triển Xây dựng",
    exchange: "HOSE",
    sectorKey: "real_estate",
    sharesOutstandingMillions: 609.8,
    baseQuarterlyRevenue: 750,
    grossMargin: 0.35,
    operatingMargin: 0.18,
    netMargin: 0.10,
    leverage: 0.58,
    currentRatio: 1.3,
    cashPctAssets: 0.15,
    capexToRevenue: 0.02,
  },
  NVL: {
    symbol: "NVL",
    name: "Công ty Cổ phần Tập đoàn Đầu tư Địa ốc No Va",
    exchange: "HOSE",
    sectorKey: "real_estate",
    sharesOutstandingMillions: 1950.1,
    baseQuarterlyRevenue: 2100,
    grossMargin: 0.32,
    operatingMargin: 0.15,
    netMargin: 0.05,
    leverage: 0.76,
    currentRatio: 1.15,
    cashPctAssets: 0.05,
    capexToRevenue: 0.02,
  },
  PDR: {
    symbol: "PDR",
    name: "Công ty Cổ phần Phát triển Bất động sản Phát Đạt",
    exchange: "HOSE",
    sectorKey: "real_estate",
    sharesOutstandingMillions: 873.1,
    baseQuarterlyRevenue: 850,
    grossMargin: 0.48,
    operatingMargin: 0.32,
    netMargin: 0.22,
    leverage: 0.52,
    currentRatio: 1.4,
    cashPctAssets: 0.10,
    capexToRevenue: 0.02,
  },
  KDH: {
    symbol: "KDH",
    name: "Công ty Cổ phần Đầu tư và Kinh doanh Nhà Khang Điền",
    exchange: "HOSE",
    sectorKey: "real_estate",
    sharesOutstandingMillions: 909.1,
    baseQuarterlyRevenue: 1250,
    grossMargin: 0.46,
    operatingMargin: 0.32,
    netMargin: 0.24,
    leverage: 0.38,
    currentRatio: 2.1,
    cashPctAssets: 0.18,
    capexToRevenue: 0.02,
  },
  NLG: {
    symbol: "NLG",
    name: "Công ty Cổ phần Đầu tư Nam Long",
    exchange: "HOSE",
    sectorKey: "real_estate",
    sharesOutstandingMillions: 384.9,
    baseQuarterlyRevenue: 1150,
    grossMargin: 0.42,
    operatingMargin: 0.26,
    netMargin: 0.18,
    leverage: 0.45,
    currentRatio: 1.8,
    cashPctAssets: 0.22,
    capexToRevenue: 0.02,
  },
  GMD: {
    symbol: "GMD",
    name: "Công ty Cổ phần Gemadept",
    exchange: "HOSE",
    sectorKey: "logistics",
    sharesOutstandingMillions: 310.5,
    baseQuarterlyRevenue: 1100,
    grossMargin: 0.45,
    operatingMargin: 0.32,
    netMargin: 0.26,
    leverage: 0.35,
    currentRatio: 1.6,
    cashPctAssets: 0.18,
    capexToRevenue: 0.12,
  },
  HAH: {
    symbol: "HAH",
    name: "Công ty Cổ phần Vận tải và Xếp dỡ Hải An",
    exchange: "HOSE",
    sectorKey: "logistics",
    sharesOutstandingMillions: 121.3,
    baseQuarterlyRevenue: 850,
    grossMargin: 0.32,
    operatingMargin: 0.22,
    netMargin: 0.18,
    leverage: 0.42,
    currentRatio: 1.4,
    cashPctAssets: 0.15,
    capexToRevenue: 0.15,
  },
  VJC: {
    symbol: "VJC",
    name: "Công ty Cổ phần Hàng không Vietjet",
    exchange: "HOSE",
    sectorKey: "logistics",
    sharesOutstandingMillions: 541.6,
    baseQuarterlyRevenue: 16500,
    grossMargin: 0.14,
    operatingMargin: 0.06,
    netMargin: 0.035,
    leverage: 0.75,
    currentRatio: 1.1,
    cashPctAssets: 0.08,
    capexToRevenue: 0.10,
  },
  HVN: {
    symbol: "HVN",
    name: "Tổng Công ty Hàng không Việt Nam (Vietnam Airlines)",
    exchange: "HOSE",
    sectorKey: "logistics",
    sharesOutstandingMillions: 2214.3,
    baseQuarterlyRevenue: 24500,
    grossMargin: 0.11,
    operatingMargin: 0.04,
    netMargin: 0.018,
    leverage: 0.95,
    currentRatio: 0.6,
    cashPctAssets: 0.05,
    capexToRevenue: 0.08,
  },
};

export function getCompanyPreset(symbol: string): CompanyPreset | null {
  const norm = symbol.trim().toUpperCase();
  return COMPANY_PRESETS[norm] ?? null;
}
