import type { PlaybookChunk } from "../types";

/** Corporate Finance (DN) expert playbook for ORCA Agent RAG. */
export const DN_PLAYBOOK: PlaybookChunk[] = [
  {
    id: "dn-cashflow",
    domain: "dn",
    title: "Đọc dòng tiền doanh nghiệp",
    keywords: [
      "dòng tiền",
      "cash flow",
      "cfo",
      "cfi",
      "cff",
      "thanh khoản",
      "tiền mặt công ty",
    ],
    body: `Thứ tự đọc: (1) Dòng tiền hoạt động (CFO) — doanh nghiệp có tự tạo tiền từ kinh doanh không. (2) Đầu tư (CFI) — CAPEX / mua tài sản. (3) Tài chính (CFF) — vay/trả nợ, tăng vốn. Cảnh báo: lãi kế toán cao nhưng CFO yếu kéo dài. Hỏi thêm: CFO, CAPEX, biến động tiền mặt cuối kỳ nếu thiếu số.`,
  },
  {
    id: "dn-working-capital",
    domain: "dn",
    title: "Vốn lưu động",
    keywords: [
      "vốn lưu động",
      "working capital",
      "phải thu",
      "tồn kho",
      "phải trả",
      "vòng quay",
    ],
    body: `Vốn lưu động ≈ tài sản ngắn hạn − nợ ngắn hạn. Áp lực khi phải thu + tồn kho phình, phải trả bị siết. Gợi ý hành động: thu hồi công nợ, tối ưu tồn kho, đàm phán kỳ hạn nhà cung cấp, không dùng nợ ngắn hạn để tài trợ tài sản dài hạn một cách mất cân đối.`,
  },
  {
    id: "dn-leverage",
    domain: "dn",
    title: "Đòn bẩy và khả năng trả lãi",
    keywords: [
      "đòn bẩy",
      "nợ",
      "trả lãi",
      "interest coverage",
      "ebit",
      "ebitda",
      "leverage",
      "vay",
    ],
    body: `Xem: tổng nợ / VCSH, nợ lãi vay / EBITDA hoặc EBIT / lãi vay (interest coverage). Coverage thấp + CFO yếu = rủi ro thanh khoản. Không khuyến khích tăng vay để “đẹp” ROE ngắn hạn. Thiếu số thì nêu công thức và số cần: EBIT/EBITDA, chi phí lãi vay, tổng nợ.`,
  },
  {
    id: "dn-profitability",
    domain: "dn",
    title: "Sinh lời: biên LN, ROE, ROA",
    keywords: [
      "roe",
      "roa",
      "biên lợi nhuận",
      "lợi nhuận",
      "margin",
      "sinh lời",
      "doanh thu",
    ],
    body: `Biên gộp / biên EBIT / biên ròng cho thấy chất lượng theo từng tầng chi phí. ROE cao cần tách: do biên tốt, vòng quay tài sản, hay đòn bẩy. ROA giúp giảm nhiễu từ đòn bẩy. So sánh theo ngành nếu có; không kết luận “tốt/xấu” chỉ từ một chỉ số một năm.`,
  },
  {
    id: "dn-capex-structure",
    domain: "dn",
    title: "CAPEX và cấu trúc vốn",
    keywords: [
      "capex",
      "cấu trúc vốn",
      "tài sản cố định",
      "đầu tư",
      "opex",
      "capital structure",
    ],
    body: `CAPEX bảo trì vs tăng trưởng: phân biệt để đánh giá dòng tiền tự do. Cấu trúc vốn: cân nợ dài hạn với tài sản dài hạn. Doanh nghiệp tăng trưởng nhanh thường đốt tiền — cần nhìn runway và khả năng gọi vốn/vay, không chỉ lãi kế toán.`,
  },
  {
    id: "dn-read-bctc",
    domain: "dn",
    title: "Khung đọc BCTC nhanh",
    keywords: [
      "bctc",
      "báo cáo tài chính",
      "financial statement",
      "cân đối",
      "kết quả kinh doanh",
    ],
    body: `Checklist 5 bước: (1) Doanh thu & biên lợi nhuận xu hướng. (2) CFO vs lợi nhuận. (3) Nợ và coverage. (4) Vốn lưu động. (5) Ghi chú bất thường (một lần, liên kết, tồn kho). Nếu khách chưa có số: đưa checklist và xin 4–6 chỉ tiêu then chốt, không đổ lỗi thiếu form.`,
  },
  {
    id: "dn-sme-cash",
    domain: "dn",
    title: "DN nhỏ / hộ kinh doanh — xoay tiền",
    keywords: [
      "hộ kinh doanh",
      "sme",
      "cửa hàng",
      "xoay vốn",
      "tiền hàng",
      "nhà cung cấp",
    ],
    body: `Ưu tiên sống còn: dòng tiền tuần/tháng, tách tiền hộ gia đình và tiền kinh doanh nếu đang lẫn. Theo dõi công nợ khách và hạn NCC. Tránh lấy lợi nhuận “trên giấy” làm cơ sở chi tiêu cá nhân. Gợi ý theo dõi đơn giản: tiền vào, tiền ra, tồn quỹ cuối tuần.`,
  },
];
