import type { PlaybookChunk } from "../types";

/**
 * Cross-cutting money situations that don't always map cleanly to PF/DN/Wealth alone.
 * Stored as domain "pf" for schema compatibility but retrieved via open search.
 */
export const MONEY_GENERAL_PLAYBOOK: PlaybookChunk[] = [
  {
    id: "mg-inflation-rates",
    domain: "pf",
    title: "Lạm phát, lãi suất và sức mua",
    keywords: [
      "lạm phát",
      "inflation",
      "lãi suất",
      "sức mua",
      "tiền mất giá",
      "gửi tiết kiệm",
      "interest rate",
    ],
    body: `Lạm phát làm tiền nhàn rỗi mất sức mua. Gửi tiết kiệm bảo vệ một phần nhưng thường không đủ nếu lạm phát cao. Nguyên tắc: (1) giữ đủ thanh khoản sống, (2) phần dài hạn cần tài sản có cơ hội tăng trưởng thực, (3) nợ lãi thả nổi tăng khi lãi suất lên — ưu tiên trả nợ lãi cao. Không hứa lợi suất cố định.`,
  },
  {
    id: "mg-fx-remittance",
    domain: "pf",
    title: "Tỷ giá và chuyển tiền",
    keywords: [
      "tỷ giá",
      "usd",
      "ngoại tệ",
      "chuyển tiền",
      "kiều hối",
      "forex",
      "đổi tiền",
      "remittance",
    ],
    body: `Tỷ giá biến động: không đổi hết một cục nếu chưa cần dùng ngay — chia nhỏ theo lịch chi tiêu. So sánh phí + tỷ giá thực nhận khi chuyển quốc tế. Tránh “đánh tỷ giá” bằng đòn bẩy nếu mục tiêu chỉ là bảo toàn vốn chi tiêu. Có số USD/VND trong câu hỏi thì ước số nhận sau phí.`,
  },
  {
    id: "mg-tax-personal",
    domain: "pf",
    title: "Thuế thu nhập cá nhân — nguyên tắc",
    keywords: [
      "thuế",
      "tncn",
      "tax",
      "khấu trừ",
      "quyết toán",
      "thuế thu nhập",
    ],
    body: `Nêu khung phổ thông: thu nhập chịu thuế, giảm trừ gia cảnh/bản thân (theo quy định hiện hành khách cần tự cập nhật), khấu trừ tại nguồn vs quyết toán. Không thay thế tư vấn thuế có giấy phép với tình huống phức tạp (nhiều nguồn thu, nước ngoài, kinh doanh). Khuyên giữ chứng từ và đối chiếu thông báo thuế.`,
  },
  {
    id: "mg-salary-negotiate",
    domain: "pf",
    title: "Đàm phán lương và thu nhập",
    keywords: [
      "đàm phán lương",
      "xin tăng lương",
      "salary",
      "offer",
      "lương mới",
      "thu nhập",
    ],
    body: `Chuẩn bị: mặt bằng thị trường (nếu biết), thành quả đo được, mức đề xuất có khoảng. Tính net sau BHXH/thuế ước tính trước khi so offer. Không chỉ so gross — so tổng đãi ngộ (thưởng, remote, học phí). Sau khi có lương mới: chỉnh lại ngân sách 50/30/20 hoặc ưu tiên nợ/quỹ khẩn cấp trước.`,
  },
  {
    id: "mg-side-income",
    domain: "pf",
    title: "Thu nhập phụ và freelance",
    keywords: [
      "thu nhập phụ",
      "side",
      "freelance",
      "làm thêm",
      "kinh doanh online",
      "passiv",
    ],
    body: `Tách: thời gian, vốn, và rủi ro pháp lý/thuế. Ưu tiên việc dùng kỹ năng sẵn có trước mô hình cần bỏ vốn lớn. Không khuyên “vay để làm already” khi chưa có dòng tiền. Thu nhập không ổn định: quỹ dự phòng nên dày hơn (6–12 tháng chi thiết yếu).`,
  },
  {
    id: "mg-scam-fraud",
    domain: "pf",
    title: "Cảnh báo lừa đảo tài chính",
    keywords: [
      "lừa đảo",
      "đa cấp",
      "việc online",
      "cam kết lãi",
      "scam",
      "otp",
      "vay nóng",
      "tín dụng đen",
    ],
    body: `Dấu hiệu đỏ: cam kết lãi cao không rủi ro, yêu cầu nộp phí trước, ép chuyển OTP/mã ví, việc online thu nhập khủng không kỹ năng, vay nóng/app không giấy phép. Khuyên: không chuyển tiền/test nhỏ, không chia sẻ OTP, báo cơ quan chức năng nếu đã mất tiền. Không hướng dẫn cách “chơi” các app đáng ngờ.`,
  },
  {
    id: "mg-buy-rent",
    domain: "wealth",
    title: "Mua nhà vs thuê nhà",
    keywords: [
      "mua nhà",
      "thuê nhà",
      "trả góp",
      "mortgage",
      "vay mua nhà",
      "buy or rent",
    ],
    body: `So sánh: tiền thuê vs (gốc+lãi+phí+bảo trì+cơ hội vốn bị khóa). Giữ thanh khoản sau khi trả trước; tránh “all-in” hết tiền vào nhà nếu chưa có quỹ khẩn cấp. Vay mua nhà: stress-test lãi suất tăng, tỷ lệ trả nợ/thu nhập. Không kết luận một chiều — phụ thuộc ổn định thu nhập, chân trời ở, và kế hoạch gia đình.`,
  },
  {
    id: "mg-invest-basics",
    domain: "wealth",
    title: "Nguyên tắc đầu tư cơ bản",
    keywords: [
      "đầu tư",
      "cổ phiếu",
      "quỹ",
      "etf",
      "trái phiếu",
      "nên mua gì",
      "chứng khoán",
      "invest",
    ],
    body: `Thứ tự: quỹ khẩn cấp + nợ lãi cao ổn → mục tiêu & chân trời → phân bổ → chọn công cụ (quỹ/ETF đa dạng thường dễ hơn stock-picking). Dollar-cost averaging khi chưa chắc timing. Không FOMO, không all-in một mã. Có hỏi mã cụ thể và có số liệu thị trường trong ghi chú thì bàn mã đó; không thì ở mức nguyên tắc.`,
  },
  {
    id: "mg-crypto-risk",
    domain: "wealth",
    title: "Crypto — rủi ro và kỷ luật vốn",
    keywords: [
      "crypto",
      "bitcoin",
      "btc",
      "ethereum",
      "eth",
      "coin",
      "token",
      "web3",
    ],
    body: `Crypto biến động mạnh, có thể mất phần lớn vốn. Chỉ dùng tiền không ảnh hưởng đời sống (thường % nhỏ tài sản đầu tư). Tránh vay để mua, tránh leverage cao, cảnh giác airdrop/token lạ. Không hứa “x2 x10”. Có giá trong ghi chú thì mô tả biến động; không có thì nguyên tắc quản trị rủi ro.`,
  },
  {
    id: "mg-loan-compare",
    domain: "pf",
    title: "So sánh khoản vay",
    keywords: [
      "vay",
      "lãi suất",
      "trả góp",
      "khoản vay",
      "đáo hạn",
      "tái cấu trúc",
      "loan",
    ],
    body: `So: lãi suất thực (APR), phí, kỳ hạn, phạt trả sớm, lãi cố định vs thả nổi. Ưu tiên giảm nợ lãi cao trước. Đáo hạn/tái cấu trúc: tính tổng tiền phải trả, không chỉ trả tháng thấp hơn. Cảnh báo vay đảo nợ chồng chất.`,
  },
  {
    id: "mg-family-money",
    domain: "pf",
    title: "Tiền trong gia đình",
    keywords: [
      "gia đình",
      "vợ chồng",
      "chia tiền",
      "nuôi con",
      "cho vay người thân",
      "bố mẹ",
    ],
    body: `Minh bạch ngân sách chung/riêng, quỹ chung cho chi phí nhà. Cho người thân vay: coi như có thể không thu hồi đủ — chỉ dùng phần không ảnh hưởng quỹ khẩn cấp. Giáo dục con: tiền tiêu vặt gắn việc nhỏ, không gắn mọi thứ vào tiền thưởng.`,
  },
  {
    id: "mg-freelancer-pricing",
    domain: "dn",
    title: "Định giá dịch vụ / freelance",
    keywords: [
      "báo giá",
      "định giá",
      "giá dịch vụ",
      "freelance",
      "hóa đơn",
      "khách hàng",
    ],
    body: `Giá ≥ chi phí thời gian + thuế/BH ước tính + đệm rủi ro revision. Đặt cọc, milestone thanh toán. Tách tài khoản KD và cá nhân. Theo dõi công nợ khách — đừng để một khách chiếm quá nhiều doanh thu nếu có thể.`,
  },
];
