import type { PlaybookChunk } from "../types";
import { MONEY_GENERAL_PLAYBOOK } from "./money-general";

/** Personal Finance (PF) expert playbook for ORCA Agent RAG. */
export const PF_PLAYBOOK: PlaybookChunk[] = [
  {
    id: "pf-short-cash",
    domain: "pf",
    title: "Quản lý tiền mặt ngắn hạn",
    keywords: [
      "còn",
      "tiền",
      "sống",
      "tiêu",
      "ngày",
      "tuần",
      "tháng",
      "ngân sách",
      "budget",
      "thiếu tiền",
      "hết tiền",
      "cash",
      "150k",
      "nghìn",
      "triệu",
      "xoay",
      "không đủ",
    ],
    body: `Khung ngắn hạn: (1) Xác định số tiền còn và số ngày phải xoay. (2) Giữ 15–25% làm dự phòng tối thiểu (hoặc ít nhất một khoản cố định nhỏ). (3) Ngân sách/ngày = (tiền − dự phòng) / số ngày. (4) Ưu tiên chỉ 3 nhóm: ăn, đi lại, khoản bắt buộc; tạm dừng mua sắm không cần thiết. (5) Nếu có thể, liệt kê 1–2 việc cắt giảm cụ thể trong tuần. Luôn tính số cụ thể khi khách cho số tiền + thời gian.`,
  },
  {
    id: "pf-income-503020",
    domain: "pf",
    title: "Chia lương / thu nhập tháng",
    keywords: [
      "lương",
      "thu nhập",
      "income",
      "chia",
      "50/30/20",
      "tiết kiệm",
      "chi tiêu",
      "tháng",
      "ngân sách tháng",
    ],
    body: `Điểm bắt đầu 50/30/20: ~50% nhu cầu thiết yếu (nhà, ăn, đi lại, tiện ích), ~30% linh hoạt, ~20% tiết kiệm/trả nợ/đầu tư. Điều chỉnh nếu thuê nhà + nợ chiếm >50%: ưu tiên thiết yếu + trả nợ trước, giảm phần linh hoạt. Hỏi thêm nếu thiếu: tiền thuê, trả nợ/tháng, người phụ thuộc. Không áp tỷ lệ cứng cho mọi người.`,
  },
  {
    id: "pf-emergency-fund",
    domain: "pf",
    title: "Quỹ khẩn cấp",
    keywords: [
      "quỹ khẩn",
      "emergency",
      "dự phòng",
      "tiết kiệm",
      "an toàn",
      "mất việc",
    ],
    body: `Quỹ khẩn cấp mục tiêu thường 3–6 tháng chi phí thiết yếu (không phải thu nhập). Giữ thanh khoản cao (tiền mặt / tiết kiệm ngắn hạn), không nhét hết vào cổ phiếu. Ưu tiên xây quỹ trước khi tăng rủi ro đầu tư nếu chưa có đệm. Có thể xây dần theo % lương mỗi tháng.`,
  },
  {
    id: "pf-debt",
    domain: "pf",
    title: "Quản lý và trả nợ cá nhân",
    keywords: [
      "nợ",
      "trả nợ",
      "vay",
      "thẻ",
      "lãi",
      "debt",
      "credit",
      "khoản vay",
      "mắc nợ",
    ],
    body: `Thứ tự ưu tiên: (1) Nợ lãi cao (thẻ tín dụng, vay tiêu dùng lãi lớn) trả trước. (2) Nợ lãi thấp có thể trả tối thiểu ổn định trong khi xây quỹ khẩn cấp tối thiểu. (3) Avalanche (lãi cao trước) hoặc Snowball (khoản nhỏ trước để tạo động lực) — nêu rõ trade-off. Không khuyên vay thêm để đầu tư khi đang nợ lãi cao.`,
  },
  {
    id: "pf-goals",
    domain: "pf",
    title: "Mục tiêu tài chính (nhà, xe, học, cưới)",
    keywords: [
      "mua nhà",
      "mua xe",
      "học phí",
      "đám cưới",
      "mục tiêu",
      "tiết kiệm mục tiêu",
      "bao giờ đủ",
    ],
    body: `Chia mục tiêu theo chân trời: <12 tháng (tiền mặt/tiết kiệm), 1–5 năm (hỗn hợp an toàn), >5 năm (có thể tăng trưởng hơn nếu đã có quỹ khẩn cấp). Công thức tham khảo: số cần / số tháng = mức tiết kiệm/tháng. Trừ khoản bắt buộc và nợ trước khi “hứa” mức tiết kiệm. Không gợi ý mã cổ phiếu cụ thể để đạt mục tiêu ngắn hạn.`,
  },
  {
    id: "pf-insurance",
    domain: "pf",
    title: "Bảo hiểm và rủi ro cá nhân",
    keywords: [
      "bảo hiểm",
      "nhân thọ",
      "sức khỏe",
      "rủi ro",
      "insurance",
    ],
    body: `Ưu tiên bảo vệ rủi ro lớn trước tối ưu lợi nhuận: bảo hiểm y tế/sức khỏe cần thiết, bảo hiểm trách nhiệm nếu có xe, nhân thọ khi có người phụ thuộc. Tránh bán chéo sản phẩm; chỉ nêu nguyên tắc lớp bảo vệ → quỹ khẩn cấp → đầu tư.`,
  },
  {
    id: "pf-cash-surplus",
    domain: "pf",
    title: "Có khoản tiền nhàn rỗi",
    keywords: [
      "nhàn rỗi",
      "đang có",
      "100 triệu",
      "tiền mặt",
      "nên làm gì",
      "đầu tư",
    ],
    body: `Không đổ hết một cục vào đầu tư. Tách 3 lớp: (A) quỹ dự phòng, (B) tiền cần dùng ≤12 tháng, (C) phần dài hạn. Chỉ phần C mới xem xét tăng trưởng. Hỏi chi phí/tháng, nợ, thời điểm cần dùng tiền trước khi đề xuất tỷ lệ.`,
  },
  {
    id: "pf-cut-spending",
    domain: "pf",
    title: "Cắt giảm chi tiêu",
    keywords: [
      "cắt giảm",
      "tiết kiệm chi",
      "tiêu nhiều",
      "lãng phí",
      "subscription",
      "chi phí",
    ],
    body: `Liệt kê chi 30 ngày gần nhất theo nhóm. Cắt trước: đăng ký ít dùng, ăn ngoài/giao hàng, mua sắm impulse. Giữ: sức khỏe, đi lại cần thiết, trả nợ. Mục tiêu giảm 10–20% chi linh hoạt trong 1 tháng rồi đánh giá lại — không cắt đến mức không bền.`,
  },
  // Cross-cutting money situations (tax, FX, scams, etc.)
  ...MONEY_GENERAL_PLAYBOOK.filter((c) => c.domain === "pf"),
];
