import type { PlaybookChunk } from "../types";

/** Wealth Management playbook for ORCA Agent RAG. */
export const WEALTH_PLAYBOOK: PlaybookChunk[] = [
  {
    id: "wm-net-worth",
    domain: "wealth",
    title: "Tài sản ròng và bức tranh gia sản",
    keywords: [
      "tài sản ròng",
      "net worth",
      "gia sản",
      "tài sản",
      "nợ",
      "wealth",
      "tổng tài sản",
    ],
    body: `Bắt đầu từ tài sản ròng = tài sản − nợ. Tách: (1) tài sản thanh khoản, (2) tài sản sinh lời / đầu tư, (3) tài sản sử dụng (nhà ở, xe). Không trộn “nhà đang ở” với vốn đầu tư khi bàn phân bổ rủi ro. Hỏi thêm nếu thiếu: tổng tài sản, tổng nợ, chi phí sống/tháng.`,
  },
  {
    id: "wm-risk-horizon",
    domain: "wealth",
    title: "Khẩu vị rủi ro và chân trời thời gian",
    keywords: [
      "khẩu vị rủi ro",
      "chịu rủi ro",
      "chân trời",
      "thời gian",
      "risk",
      "horizon",
      "mức rủi ro",
    ],
    body: `Phân bổ phụ thuộc chân trời và khả năng chịu biến động, không chỉ “muốn lợi nhuận cao”. <3 năm: ưu tiên bảo toàn và thanh khoản. 3–7 năm: hỗn hợp. >7–10 năm: có thể tăng phần tăng trưởng nếu đã có quỹ khẩn cấp và nợ lãi cao đã kiểm soát. Không gán một tỷ lệ cố định cho mọi người.`,
  },
  {
    id: "wm-allocation",
    domain: "wealth",
    title: "Phân bổ tài sản (asset allocation)",
    keywords: [
      "phân bổ",
      "asset allocation",
      "danh mục",
      "cổ phiếu",
      "trái phiếu",
      "tiền mặt",
      "vàng",
      "bất động sản",
      "tỷ trọng",
    ],
    body: `Khung lớp: tiền mặt/dự phòng → thu nhập cố định / ổn định → tăng trưởng (cổ phiếu, quỹ) → vệ tinh (vàng, BĐS đầu tư…) tùy hiểu biết và thanh khoản. Nêu tỷ lệ tham khảo theo khẩu vị (thận trọng / cân bằng / tăng trưởng) và nhấn mạnh đây là điểm xuất phát, cần chỉnh theo nợ, thu nhập, mục tiêu. Không liệt kê basket mã VNM/FPT/VCB cố định.`,
  },
  {
    id: "wm-diversify",
    domain: "wealth",
    title: "Đa dạng hóa và tập trung rủi ro",
    keywords: [
      "đa dạng hóa",
      "tập trung",
      "diversification",
      "ngành",
      "rủi ro",
      "một mã",
    ],
    body: `Tránh tập trung quá mức một mã, một ngành, hoặc toàn bộ vào BĐS không thanh khoản. Đa dạng hóa theo nhóm tài sản và theo nguồn thu nhập (không để cùng một công ty/ngành quyết định cả lương lẫn danh mục). Cảnh báo khi >30–40% tài sản đầu tư nằm ở một vị thế đơn lẻ mà không có lý do đặc biệt.`,
  },
  {
    id: "wm-rebalance",
    domain: "wealth",
    title: "Tái cân bằng danh mục",
    keywords: [
      "tái cân bằng",
      "rebalance",
      "rebalancing",
      "chỉnh tỷ trọng",
      "định kỳ",
    ],
    body: `Tái cân bằng định kỳ (ví dụ 6–12 tháng) hoặc khi tỷ trọng lệch ngưỡng (vd ±5 điểm %). Mục tiêu: giữ mức rủi ro đã chọn, không phải “bắt đáy”. Ưu tiên dùng dòng tiền mới (lương, thưởng) để cân bằng trước khi bán tháo. Nhắc chi phí giao dịch và thuế nếu liên quan.`,
  },
  {
    id: "wm-liquidity",
    domain: "wealth",
    title: "Thanh khoản và quỹ dự phòng trong wealth",
    keywords: [
      "thanh khoản",
      "dự phòng",
      "quỹ khẩn",
      "tiền mặt",
      "liquidity",
      "emergency",
    ],
    body: `Trước phần tăng trưởng dài hạn: giữ quỹ chi tiêu 3–6 tháng (hoặc cao hơn nếu thu nhập biến động). Không dùng tiền cần trong 12 tháng để chịu rủi ro thị trường lớn. Tách rõ “tiền sống” và “tiền đầu tư”.`,
  },
  {
    id: "wm-retirement",
    domain: "wealth",
    title: "Hưu trí và mục tiêu dài hạn",
    keywords: [
      "hưu trí",
      "nghỉ hưu",
      "retirement",
      "dài hạn",
      "lương hưu",
      "tích lũy",
    ],
    body: `Ước nhu cầu chi tiêu lúc hưu (theo giá trị thực), số năm tích lũy, và khoảng đóng góp đều đặn. Có thể dùng tư duy “tỷ lệ tiết kiệm / thu nhập” và chân trời dài để chấp nhận biến động hợp lý. Không cam kết lợi suất cố định. Kết hợp bảo hiểm/rủi ro sức khỏe khi có người phụ thuộc.`,
  },
  {
    id: "wm-lifecycle",
    domain: "wealth",
    title: "Vòng đời tài chính gia đình",
    keywords: [
      "gia đình",
      "con cái",
      "kết hôn",
      "thừa kế",
      "lifecycle",
      "giai đoạn",
    ],
    body: `Điều chỉnh phân bổ theo giai đoạn: độc thân / mới lập gia đình / có con / cận hưu. Ưu tiên bảo vệ thu nhập và quỹ giáo dục trước khi tối đa hóa rủi ro. Tránh tư vấn “all-in” một kênh vì FOMO. Hỏi giai đoạn sống và nghĩa vụ tài chính hiện tại nếu chưa rõ.`,
  },
];
