import { and, desc, eq } from "drizzle-orm";
import { NextRequest } from "next/server";
import { db } from "@/db";
import { stockNewsEvents } from "@/db/schema";
import { checkRateLimit, fail, handleError, ok } from "@/lib/api";

export async function GET(req: NextRequest, ctx: { params: Promise<{ symbol: string }> }) { const limited = checkRateLimit(req, 60); if (limited) return limited; const symbol = (await ctx.params).symbol.toUpperCase(); if (!/^[A-Z0-9]{1,15}$/.test(symbol)) return fail("Invalid symbol", 400); try { const rows = await db.select().from(stockNewsEvents).where(eq(stockNewsEvents.symbol, symbol)).orderBy(desc(stockNewsEvents.publishedAt)).limit(100); return ok({ symbol, items: rows, count: rows.length }); } catch (err) { return handleError(err, `news-events:${symbol}`); } }

export async function POST(req: NextRequest, ctx: { params: Promise<{ symbol: string }> }) { const limited = checkRateLimit(req, 30); if (limited) return limited; const symbol = (await ctx.params).symbol.toUpperCase(); if (!/^[A-Z0-9]{1,15}$/.test(symbol)) return fail("Invalid symbol", 400); try { const body = await req.json() as { eventKey?: string; category?: string; impact?: string; sentiment?: number; sourceQuality?: number; publishedAt?: string; payload?: Record<string, unknown> }; if (!body.eventKey || !body.category || !body.impact || !body.publishedAt || !body.payload) return fail("news event payload không hợp lệ", 400); const [saved] = await db.insert(stockNewsEvents).values({ symbol, eventKey: body.eventKey.slice(0, 220), category: body.category.slice(0, 30), impact: body.impact.slice(0, 15), sentiment: typeof body.sentiment === "number" ? body.sentiment : 0, sourceQuality: typeof body.sourceQuality === "number" ? body.sourceQuality : 0, publishedAt: new Date(body.publishedAt), payload: body.payload }).onConflictDoUpdate({ target: [stockNewsEvents.symbol, stockNewsEvents.eventKey], set: { category: body.category.slice(0, 30), impact: body.impact.slice(0, 15), sentiment: typeof body.sentiment === "number" ? body.sentiment : 0, sourceQuality: typeof body.sourceQuality === "number" ? body.sourceQuality : 0, payload: body.payload } }).returning(); return ok(saved); } catch (err) { return handleError(err, `news-events:${symbol}`); } }
