import type { CompanyProfile } from "@/lib/company-profile";
import type { SectorBenchmark } from "@/lib/industry-benchmarks";
import type { CrossModuleContext } from "@/lib/stock-intelligence/cross-module-engine";

export type MoatDimension = "brand" | "cost_advantage" | "technology" | "distribution" | "switching_cost" | "network_effect" | "regulation";
export interface MoatFactor { dimension: MoatDimension; label: string; score: number | null; evidence: string; source: "company-profile" | "sector-benchmark" | "market-context" | "inference"; confidence: number; coverage: "direct" | "proxy" | "unknown"; }
export interface BusinessIntelligence { symbol: string; company: { name: string; sector: string; industry: string; description: string }; segments: Array<{ name: string; description: string; confidence: number; source: string }>; moat: { score: number; rating: "weak" | "moderate" | "strong" | "insufficient_data"; factors: MoatFactor[]; caveat: string }; growthDrivers: Array<{ driver: string; direction: "positive" | "negative" | "uncertain"; evidence: string; confidence: number }>; competitivePosition: { label: "leader" | "challenger" | "specialist" | "uncertain"; rationale: string; confidence: number }; industryPosition: { sector: string; benchmarkDescription: string; context: string; confidence: number }; dataConfidence: number; disclosure: string; }

function clamp(n: number) { return Math.max(0, Math.min(100, Math.round(n))); }
function scoreFromBenchmark(value: number, median: number, scale: number) { return clamp(50 + ((value - median) / Math.max(scale, 0.01)) * 25); }

export function buildBusinessIntelligence(input: { profile: CompanyProfile; benchmark: SectorBenchmark; crossModule: CrossModuleContext; financial?: { roe?: number | null; netMargin?: number | null; revenueGrowth?: number | null; debtRatio?: number | null } | null }): BusinessIntelligence {
  const financial = input.financial ?? {};
  const factors: MoatFactor[] = [
    { dimension: "brand", label: "Thương hiệu", score: null, evidence: "Chưa có dữ liệu nhận diện thương hiệu, khả năng định giá hoặc khảo sát khách hàng theo doanh nghiệp.", source: "inference", confidence: 0, coverage: "unknown" },
    { dimension: "cost_advantage", label: "Lợi thế chi phí", score: financial.netMargin == null ? null : scoreFromBenchmark(financial.netMargin, input.benchmark.netMargin, 0.08), evidence: financial.netMargin == null ? "Chưa có biên lợi nhuận ròng actual theo doanh nghiệp." : `Biên lợi nhuận ròng ${financial.netMargin.toFixed(2)} được so với benchmark ngành ${input.benchmark.netMargin.toFixed(2)}; đây là proxy, không phải bằng chứng lợi thế chi phí.`, source: financial.netMargin == null ? "sector-benchmark" : "inference", confidence: financial.netMargin == null ? 0 : 0.55, coverage: financial.netMargin == null ? "unknown" : "proxy" },
    { dimension: "technology", label: "Công nghệ", score: null, evidence: "Chưa có dữ liệu R&D, bằng sáng chế hoặc khác biệt sản phẩm được xác minh.", source: "sector-benchmark", confidence: 0, coverage: "unknown" },
    { dimension: "distribution", label: "Phân phối", score: null, evidence: "Chưa có dữ liệu độ phủ kênh, điểm bán hoặc mức độ tập trung theo doanh nghiệp.", source: "inference", confidence: 0, coverage: "unknown" },
    { dimension: "switching_cost", label: "Chi phí chuyển đổi", score: null, evidence: "Mô hình kinh doanh hiện chưa có dữ liệu retention, churn hoặc thời hạn hợp đồng để xác nhận chi phí chuyển đổi.", source: "inference", confidence: 0, coverage: "unknown" },
    { dimension: "network_effect", label: "Hiệu ứng mạng lưới", score: null, evidence: "Chưa có chỉ số hiệu ứng mạng lưới hoặc tăng trưởng người dùng theo doanh nghiệp.", source: "inference", confidence: 0, coverage: "unknown" },
    { dimension: "regulation", label: "Lợi thế pháp lý/quy định", score: null, evidence: "Chưa có dữ liệu giấy phép, hạn ngạch hoặc rào cản pháp lý được xác minh.", source: "inference", confidence: 0, coverage: "unknown" },
  ];
  const scoredFactors = factors.filter((factor): factor is MoatFactor & { score: number } => factor.score != null && factor.coverage !== "unknown");
  const score = scoredFactors.length ? clamp(scoredFactors.reduce((sum, factor) => sum + factor.score * factor.confidence, 0) / Math.max(0.1, scoredFactors.reduce((sum, factor) => sum + factor.confidence, 0))) : 0;
  const confidence = factors.reduce((sum, factor) => sum + factor.confidence, 0) / factors.length;
  const coverage = scoredFactors.length / factors.length;
  const rating = coverage < 0.4 || confidence < 0.28 ? "insufficient_data" : score >= 68 ? "strong" : score >= 52 ? "moderate" : "weak";
  const growthDrivers = [
    { driver: "Động lượng ngành", direction: input.crossModule.industry.sectorChangePct == null ? "uncertain" as const : input.crossModule.industry.sectorChangePct >= 0 ? "positive" as const : "negative" as const, evidence: input.crossModule.industry.sectorChangePct == null ? "Chưa có sector change." : `Sector change ${input.crossModule.industry.sectorChangePct.toFixed(2)}%.`, confidence: input.crossModule.industry.confidence },
    { driver: "Bối cảnh thị trường", direction: input.crossModule.market.regime.includes("BULLISH") ? "positive" as const : input.crossModule.market.regime.includes("RISK_OFF") || input.crossModule.market.regime.includes("BEARISH") ? "negative" as const : "uncertain" as const, evidence: `${input.crossModule.market.regimeLabel}; risk ${input.crossModule.market.risk}.`, confidence: input.crossModule.market.confidence },
    { driver: "Commodity exposure", direction: input.crossModule.signals.find((signal) => signal.module === "commodity")?.direction === "positive" ? "positive" as const : input.crossModule.signals.find((signal) => signal.module === "commodity")?.direction === "negative" ? "negative" as const : "uncertain" as const, evidence: input.crossModule.signals.find((signal) => signal.module === "commodity")?.evidence ?? "Chưa có mapping.", confidence: input.crossModule.signals.find((signal) => signal.module === "commodity")?.confidence ?? 0 },
  ];
  const competitivePosition = coverage < 0.4 ? "uncertain" : score >= 68 ? "leader" : score >= 52 ? "challenger" : "uncertain";
  return { symbol: input.profile.symbol, company: { name: input.profile.name, sector: input.profile.sector, industry: input.profile.industry, description: input.profile.description }, segments: [{ name: input.profile.industry, description: "Phân khúc chính được suy ra từ phân loại ngành; chưa có công bố phân khúc theo doanh nghiệp.", confidence: 0.3, source: "industry-benchmark" }], moat: { score, rating, factors, caveat: "Điểm hào kinh tế chỉ sử dụng bằng chứng trực tiếp hoặc proxy có gắn coverage. Các chiều thiếu dữ liệu giữ nguyên trạng thái chưa xác định, không mặc định về 50/100." }, growthDrivers, competitivePosition: { label: competitivePosition, rationale: coverage < 0.4 ? "Chưa đủ độ phủ bằng chứng để xếp vị thế cạnh tranh." : `Vị thế được suy luận từ proxy hào kinh tế ${score}/100 và bối cảnh ngành; chưa có xếp hạng thị phần actual.`, confidence: Math.min(confidence, input.crossModule.industry.confidence) }, industryPosition: { sector: input.profile.sector, benchmarkDescription: input.profile.benchmarkDescription, context: `Bối cảnh ngành: ${input.crossModule.industry.industry}; trạng thái thị trường: ${input.crossModule.market.regimeLabel}.`, confidence: input.crossModule.industry.confidence }, dataConfidence: Math.min(confidence, input.crossModule.dataConfidence), disclosure: "Business Intelligence sử dụng hồ sơ doanh nghiệp, benchmark ngành và bối cảnh thị trường/hàng hóa có sẵn. Các chiều hào kinh tế thiếu dữ liệu được gắn unknown/insufficient confidence và không được suy diễn thành bằng chứng doanh nghiệp." };
}
