import type { CompanyProfile } from "@/lib/company-profile";
import type { SectorBenchmark } from "@/lib/industry-benchmarks";
import type { CrossModuleContext } from "@/lib/stock-intelligence/cross-module-engine";

export type MoatDimension = "brand" | "cost_advantage" | "technology" | "distribution" | "switching_cost" | "network_effect" | "regulation";
export interface MoatFactor { dimension: MoatDimension; label: string; score: number; evidence: string; source: "company-profile" | "sector-benchmark" | "market-context" | "inference"; confidence: number; }
export interface BusinessIntelligence { symbol: string; company: { name: string; sector: string; industry: string; description: string }; segments: Array<{ name: string; description: string; confidence: number; source: string }>; moat: { score: number; rating: "weak" | "moderate" | "strong" | "insufficient_data"; factors: MoatFactor[]; caveat: string }; growthDrivers: Array<{ driver: string; direction: "positive" | "negative" | "uncertain"; evidence: string; confidence: number }>; competitivePosition: { label: "leader" | "challenger" | "specialist" | "uncertain"; rationale: string; confidence: number }; industryPosition: { sector: string; benchmarkDescription: string; context: string; confidence: number }; dataConfidence: number; disclosure: string; }

function clamp(n: number) { return Math.max(0, Math.min(100, Math.round(n))); }
function scoreFromBenchmark(value: number, median: number, scale: number) { return clamp(50 + ((value - median) / Math.max(scale, 0.01)) * 25); }

export function buildBusinessIntelligence(input: { profile: CompanyProfile; benchmark: SectorBenchmark; crossModule: CrossModuleContext; financial?: { roe?: number | null; netMargin?: number | null; revenueGrowth?: number | null; debtRatio?: number | null } | null }): BusinessIntelligence {
  const financial = input.financial ?? {};
  const factors: MoatFactor[] = [
    { dimension: "brand", label: "Thương hiệu", score: 50, evidence: "Chưa có dữ liệu brand awareness, pricing power hoặc customer survey theo doanh nghiệp.", source: "inference", confidence: 0.2 },
    { dimension: "cost_advantage", label: "Lợi thế chi phí", score: financial.netMargin == null ? 50 : scoreFromBenchmark(financial.netMargin, input.benchmark.netMargin, 0.08), evidence: financial.netMargin == null ? "Chưa có net margin actual theo doanh nghiệp." : `Net margin ${financial.netMargin.toFixed(2)} được so với benchmark ngành ${input.benchmark.netMargin.toFixed(2)}.`, source: financial.netMargin == null ? "sector-benchmark" : "inference", confidence: financial.netMargin == null ? 0.25 : 0.55 },
    { dimension: "technology", label: "Công nghệ", score: input.profile.sector.toLowerCase().includes("công nghệ") ? 65 : 45, evidence: "Điểm ngành chỉ là proxy; chưa có dữ liệu R&D, bằng sáng chế hoặc sản phẩm độc quyền.", source: "sector-benchmark", confidence: 0.25 },
    { dimension: "distribution", label: "Phân phối", score: 50, evidence: "Chưa có dữ liệu độ phủ kênh, điểm bán hoặc concentration theo doanh nghiệp.", source: "inference", confidence: 0.2 },
    { dimension: "switching_cost", label: "Chi phí chuyển đổi", score: 45, evidence: "Chưa có retention, churn hoặc contract duration theo doanh nghiệp.", source: "inference", confidence: 0.2 },
    { dimension: "network_effect", label: "Hiệu ứng mạng lưới", score: 35, evidence: "Chưa có metric network effect hoặc user growth theo doanh nghiệp.", source: "inference", confidence: 0.15 },
    { dimension: "regulation", label: "Lợi thế pháp lý/quy định", score: 50, evidence: "Chưa có dữ liệu license, quota hoặc regulatory barrier được xác minh.", source: "inference", confidence: 0.2 },
  ];
  const score = clamp(factors.reduce((sum, factor) => sum + factor.score * factor.confidence, 0) / Math.max(0.1, factors.reduce((sum, factor) => sum + factor.confidence, 0)));
  const confidence = factors.reduce((sum, factor) => sum + factor.confidence, 0) / factors.length;
  const rating = confidence < 0.28 ? "insufficient_data" : score >= 68 ? "strong" : score >= 52 ? "moderate" : "weak";
  const growthDrivers = [
    { driver: "Động lượng ngành", direction: input.crossModule.industry.sectorChangePct == null ? "uncertain" as const : input.crossModule.industry.sectorChangePct >= 0 ? "positive" as const : "negative" as const, evidence: input.crossModule.industry.sectorChangePct == null ? "Chưa có sector change." : `Sector change ${input.crossModule.industry.sectorChangePct.toFixed(2)}%.`, confidence: input.crossModule.industry.confidence },
    { driver: "Bối cảnh thị trường", direction: input.crossModule.market.regime.includes("BULLISH") ? "positive" as const : input.crossModule.market.regime.includes("RISK_OFF") || input.crossModule.market.regime.includes("BEARISH") ? "negative" as const : "uncertain" as const, evidence: `${input.crossModule.market.regimeLabel}; risk ${input.crossModule.market.risk}.`, confidence: input.crossModule.market.confidence },
    { driver: "Commodity exposure", direction: input.crossModule.signals.find((signal) => signal.module === "commodity")?.direction === "positive" ? "positive" as const : input.crossModule.signals.find((signal) => signal.module === "commodity")?.direction === "negative" ? "negative" as const : "uncertain" as const, evidence: input.crossModule.signals.find((signal) => signal.module === "commodity")?.evidence ?? "Chưa có mapping.", confidence: input.crossModule.signals.find((signal) => signal.module === "commodity")?.confidence ?? 0 },
  ];
  const competitivePosition = score >= 68 ? "leader" : score >= 52 ? "challenger" : "uncertain";
  return { symbol: input.profile.symbol, company: { name: input.profile.name, sector: input.profile.sector, industry: input.profile.industry, description: input.profile.description }, segments: [{ name: input.profile.industry, description: "Phân khúc chính được suy ra từ industry classification; chưa có segment disclosure theo doanh nghiệp.", confidence: 0.3, source: "industry-benchmark" }], moat: { score, rating, factors, caveat: "Moat score hiện là scorecard định hướng nghiên cứu. Không được coi là xác nhận competitive advantage khi chưa có dữ liệu segment, pricing power, retention, R&D hoặc filings theo doanh nghiệp." }, growthDrivers, competitivePosition: { label: competitivePosition, rationale: `Vị thế được suy luận từ moat proxy ${score}/100 và industry context; chưa có market-share ranking actual.`, confidence: Math.min(confidence, input.crossModule.industry.confidence) }, industryPosition: { sector: input.profile.sector, benchmarkDescription: input.profile.benchmarkDescription, context: `Industry context: ${input.crossModule.industry.industry}; market regime: ${input.crossModule.market.regimeLabel}.`, confidence: input.crossModule.industry.confidence }, dataConfidence: Math.min(confidence, input.crossModule.dataConfidence), disclosure: "Business Intelligence sử dụng company profile, sector benchmark và cross-module market/commodity context có sẵn. Các moat dimensions thiếu dữ liệu doanh nghiệp được gắn inference/insufficient confidence, không bịa thông tin về doanh nghiệp." };
}
