import { randomUUID } from "node:crypto";
import { eq } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { stockUserPreferences } from "@/db/schema";
import { checkRateLimit, fail, handleError, ok } from "@/lib/api";

function session(req: NextRequest) { const existing = req.cookies.get("vnstock_session")?.value; const valid = Boolean(existing && /^[a-f0-9-]{36}$/i.test(existing)); return { id: valid ? existing as string : randomUUID(), isNew: !valid }; }
function cookie(res: NextResponse, id: string, isNew: boolean) { if (isNew) res.cookies.set("vnstock_session", id, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 31536000, path: "/" }); return res; }
export async function GET(req: NextRequest) { const limited = checkRateLimit(req, 60); if (limited) return limited; const s = session(req); try { const [row] = await db.select().from(stockUserPreferences).where(eq(stockUserPreferences.sessionId, s.id)).limit(1); return cookie(ok(row ?? { riskProfile: "balanced", horizon: "medium", maxPositionPct: 10, alertThresholdPct: 5, includeEstimateData: false, source: "default" }), s.id, s.isNew); } catch (err) { return handleError(err, "stock-preferences_get"); } }
export async function PUT(req: NextRequest) { const limited = checkRateLimit(req, 30); if (limited) return limited; const s = session(req); try { const body = await req.json() as { riskProfile?: "conservative" | "balanced" | "aggressive"; horizon?: "short" | "medium" | "long"; maxPositionPct?: number; alertThresholdPct?: number; includeEstimateData?: boolean }; const riskProfile = body.riskProfile ?? "balanced"; const horizon = body.horizon ?? "medium"; const maxPositionPct = body.maxPositionPct ?? (riskProfile === "conservative" ? 5 : riskProfile === "aggressive" ? 20 : 10); const alertThresholdPct = body.alertThresholdPct ?? (riskProfile === "conservative" ? 3 : riskProfile === "aggressive" ? 8 : 5); if (!["conservative", "balanced", "aggressive"].includes(riskProfile) || !["short", "medium", "long"].includes(horizon) || !Number.isFinite(maxPositionPct) || maxPositionPct <= 0 || maxPositionPct > 100 || !Number.isFinite(alertThresholdPct) || alertThresholdPct <= 0 || alertThresholdPct > 100) return fail("preferences payload không hợp lệ", 400); const [saved] = await db.insert(stockUserPreferences).values({ sessionId: s.id, riskProfile, horizon, maxPositionPct, alertThresholdPct, includeEstimateData: body.includeEstimateData ?? false, updatedAt: new Date() }).onConflictDoUpdate({ target: stockUserPreferences.sessionId, set: { riskProfile, horizon, maxPositionPct, alertThresholdPct, includeEstimateData: body.includeEstimateData ?? false, updatedAt: new Date() } }).returning(); return cookie(ok(saved), s.id, s.isNew); } catch (err) { return handleError(err, "stock-preferences_put"); } }
