import { randomUUID } from "node:crypto";
import { and, desc, eq, isNull } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { stockAlertEvents, stockAlertRules } from "@/db/schema";
import { checkRateLimit, fail, handleError, ok } from "@/lib/api";
function session(req: NextRequest) { const existing = req.cookies.get("vnstock_session")?.value; const valid = Boolean(existing && /^[a-f0-9-]{36}$/i.test(existing)); return { id: valid ? existing as string : randomUUID(), isNew: !valid }; }
function cookie(res: NextResponse, id: string, isNew: boolean) { if (isNew) res.cookies.set("vnstock_session", id, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 31536000, path: "/" }); return res; }
function symbol(value?: string) { const s = value?.toUpperCase().trim() ?? ""; return /^[A-Z0-9]{1,15}$/.test(s) ? s : null; }
export async function GET(req: NextRequest) { const limited = checkRateLimit(req, 60); if (limited) return limited; const s = session(req); try { const [rules, events] = await Promise.all([db.select().from(stockAlertRules).where(eq(stockAlertRules.sessionId, s.id)).orderBy(desc(stockAlertRules.createdAt)), db.select().from(stockAlertEvents).where(and(eq(stockAlertEvents.sessionId, s.id), isNull(stockAlertEvents.readAt))).orderBy(desc(stockAlertEvents.createdAt)).limit(100)]); return cookie(ok({ rules, unreadEvents: events, unreadCount: events.length }), s.id, s.isNew); } catch (err) { return handleError(err, "stock-alerts_get"); } }
export async function POST(req: NextRequest) { const limited = checkRateLimit(req, 30); if (limited) return limited; const s = session(req); try { const body = await req.json() as { symbol?: string; type?: "price" | "technical" | "pattern" | "volume" | "fundamental" | "news" | "valuation"; threshold?: number | null }; const sym = symbol(body.symbol); if (!sym || !body.type || (body.threshold != null && !Number.isFinite(body.threshold))) return fail("alert rule payload không hợp lệ", 400); const [rule] = await db.insert(stockAlertRules).values({ sessionId: s.id, symbol: sym, type: body.type, threshold: body.threshold ?? null }).returning(); return cookie(ok(rule), s.id, s.isNew); } catch (err) { return handleError(err, "stock-alerts_post"); } }
export async function PATCH(req: NextRequest) { const limited = checkRateLimit(req, 30); if (limited) return limited; const s = session(req); try { const body = await req.json() as { ruleId?: number; enabled?: boolean; eventId?: number; read?: boolean }; if (body.eventId) { const [event] = await db.update(stockAlertEvents).set({ readAt: body.read === false ? null : new Date() }).where(and(eq(stockAlertEvents.id, body.eventId), eq(stockAlertEvents.sessionId, s.id))).returning(); return cookie(ok(event ?? null), s.id, s.isNew); } if (!body.ruleId || typeof body.enabled !== "boolean") return fail("alert update payload không hợp lệ", 400); const [rule] = await db.update(stockAlertRules).set({ enabled: body.enabled }).where(and(eq(stockAlertRules.id, body.ruleId), eq(stockAlertRules.sessionId, s.id))).returning(); return cookie(ok(rule ?? null), s.id, s.isNew); } catch (err) { return handleError(err, "stock-alerts_patch"); } }
export async function DELETE(req: NextRequest) { const limited = checkRateLimit(req, 30); if (limited) return limited; const s = session(req); const id = Number(req.nextUrl.searchParams.get("ruleId")); if (!Number.isInteger(id)) return fail("Invalid ruleId", 400); try { await db.delete(stockAlertRules).where(and(eq(stockAlertRules.id, id), eq(stockAlertRules.sessionId, s.id))); return cookie(ok({ id, removed: true }), s.id, s.isNew); } catch (err) { return handleError(err, "stock-alerts_delete"); } }
